package presentation

// Code generated by 1_codegen_test.go DO NOT EDIT.

import (
	"olshop1/domain"
)

var allCommands = []string{
	domain.GuestDebugAction,
	domain.GuestLoginAction,
	domain.GuestRegisterAction,
	domain.UserLogoutAction,
}

// Code generated by 1_codegen_test.go DO NOT EDIT.
